site_name: CiviSEPA
site_description: SEPA Direct Debit Extension
repo_url: https://github.com/Project60/org.project60.sepa
theme: material
pages:
- Introduction: index.md
- Sepa Basics: sepa-basics.md
- Things to Consider: consider.md
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc(permalink=true)
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark
